name: Algorithm2 CI

# workflow will run on push and pull request to master
on:
  push:
  pull_request:
    branches:
      - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Build docker image using Dockerfile root
      # and run Docker container
      - name: Build and run Docker image
        run: |
          docker build -t myapp .
          docker run -d -p 5000:5000 myapp